package com.guidejourney.model.enums;

public enum InterestArea {
    SOFTWARE_DEVELOPMENT, 
    WEB_DEVELOPMENT,
    MOBILE_DEVELOPMENT,
    DATA_SCIENCE,
    MACHINE_LEARNING,
    ARTIFICIAL_INTELLIGENCE,
    CYBERSECURITY,
    NETWORKING,
    DATABASE_ADMINISTRATION,
    CLOUD_COMPUTING,
    GAME_DEVELOPMENT,
    UI_UX_DESIGN,
    IT_SUPPORT
}
