package com.guidejourney.model.enums;

public enum InterestArea {
    DESARROLLO_SOFTWARE,
    DESARROLLO_WEB,
    DESARROLLO_MOVIL,
    CIENCIA_DE_DATOS,
    APRENDIZAJE_AUTOMATICO,
    INTELIGENCIA_ARTIFICIAL,
    CIBERSEGURIDAD,
    REDES,
    ADMINISTRACION_DE_BASES_DE_DATOS,
    COMPUTACION_EN_LA_NUBE,
    DESARROLLO_DE_VIDEOJUEGOS,
    DISENO_UI_UX,
    SOPORTE_TECNICO
}
